### ISSUE TITLE
Ruby 2.6 warning with splat operator

### ISSUE THREAD

**Issue by smandegar** [dry-rb/dry-struct#110]
It seems that with Ruby 2.6, using a double splat operator on a hash to initialize a new struct results in a Ruby warning about the argument being passed in as a single hash.

For example:
```
> args = { test_1: 1, test_2: 2 }
=> {:test_1=>1, :test_2=>2}
> Dry::Struct.new **args

/usr/local/bundle/gems/dry-struct-0.7.0/lib/dry/struct/class_interface.rb:225: warning: in `new': the last argument was passed as a single Hash
(irb):6: warning: although a splat keyword arguments here
```

**Comment by flash-gordon** [comment]
Yes, `Dry::Struct.new` accepts a hash, not keyword arguments, that's why you see this warning. It is intended, you're supposed to pass a hash. In complex cases, you may want to add hash braces, this will indicate to Ruby you're passing a hash.
```ruby
MyStruct.new({ **args1, **args2, something_else: 3, **args4 })
```

**Comment by smandegar** [comment]
Your documentation does not show this gem being used like that: https://dry-rb.org/gems/dry-struct/

eg: `loc1 = Location.new(lat: 1.23, lng: 4.56)`

I would suggest updating the documentation if Dry::Struct is not meant to be using keyword arguments

**Comment by flash-gordon** [comment]
I know it's confusing but this usage does not produce a warning. In this case, values are passed as a hash because ruby allows omitting curly braces for the last argument of a method provided it's a hash.

**Comment by smandegar** [comment]
Indeed, that's where the confusion was. Thank you for the clarification however.
