### ISSUE TITLE
How to use a double with an `Instance` attribute?

### ISSUE THREAD

**Issue by fotanus** [dry-rb/dry-struct#124]
Hello,

Is it possible for a double to bypass the `Instance` check on a dry-struct attribute? For instance:

```ruby
require 'dry-struct'
require 'spec_helper'

class B
end

class A < ::Dry::Struct
  include Dry::Types.module
  constructor_type(:schema)
  attribute :b, Instance(B).optional
end


describe 'something' do
  it 'test' do
    b = instance_double('B')
    expect(
      A.new(b: b)
    ).to be
  end
end
```

I've tried to mock several methods from both `B` and `b` and was not able to make this test pass.

**Comment by solnic** [comment]
Please don't use issues for support questions and instead post a message on [our forum](https://discourse.dry-rb.org). See [CONTRIBUTING.md](https://github.com/dry-rb/dry-struct/blob/master/CONTRIBUTING.md) for more information.

**Comment by fotanus** [comment]
OK, thank you!
