### ISSUE TITLE
Array.of(...).optional does not work as expected

### ISSUE THREAD

**Issue by gorodulin** [dry-rb/dry-struct#135]
Can't define optional array attributes with  `Array.of(...).optional`

**To Reproduce**

```ruby
require "dry-struct"
class TestStruct < Dry::Struct
  attribute :id, Dry::Types["string"]
  attribute :arr, Dry::Types["array"].of(Dry::Types["string"]).optional
end

TestStruct.new(id: "abc")
```

will raise:
`[TestStruct.new] :arr is missing in Hash input (Dry::Struct::Error)`

**Expected behavior**

I expect it not to raise any errors.

**Your environment**

dry-struct (1.1.1)

- Ruby version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
- OS: Docker container `FROM ruby:2.6.5`

**Comment by flash-gordon** [comment]
This is not a bug. `.optional` is related to the value, to the key. If you want the key to be optional, use `attribute?`. See the docs: https://dry-rb.org/gems/dry-struct/1.0/recipes/#tolerance-to-missing-keys
