### ISSUE TITLE
Optional string keys set with `attribute?` ignore input values

### ISSUE THREAD

**Issue by gorodulin** [dry-rb/dry-struct#136]
Structs with optional string keys defined via `attribute? ...` treat these keys as unknown. Symbolic keys work fine.

**To Reproduce**

```ruby
class MyStruct < Dry::Struct
  schema schema.strict
  attribute "attrOne", Types::String
  attribute? "attrTwo", Types::String
  attribute? "attrThree", Types::String.optional
end

struct = MyStruct.new("attrOne" => "value1", "attrTwo" => "value2")
# => Dry::Struct::Error: [MyStruct.new] unexpected keys ["attrTwo"] in Hash input
```

Thanks to `schema schema.strict` I noticed this behaviour in my deeply nested structs.
Without it the structure swallows optional string keys silently and set values to `nil`.

**Expected behavior**

```ruby
struct = MyStruct.new("attrOne" => "value1", "attrTwo" => "value2")
# => #<MyStruct attrOne="value1" attrTwo="value2" attrThree=nil>
```

```ruby
struct = MyStruct.new("attrOne" => "value1")
# => #<MyStruct attrOne="value1" attrThree=nil>
# NOTE: imo `struct.to_hash` should not contain `"attrTwo" => nil` bc the key is defined as optional
```

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.6.5
- OS: Official ruby Docker container

**Comment by flash-gordon** [comment]
String keys are not supported and never were. You can define a transformation for keys like `transform_keys(&:to_sym)` that will turn strings into symbols. I'll report an issue to dry-types to reject schemas with non-symbol keys to make it clear.
