### ISSUE TITLE
Strange validations being performed after include `Dry.types`

### ISSUE THREAD

**Issue by rwehresmann** [dry-rb/dry-struct#152]
After updateing the `include` of a class from `Dry::Types.module` to `Dry.types`, some strange validations are being performed:

```
Dry::Struct::Error:
       [MasterOrderBuilder.new] {:amount=>1000} (Hash) has invalid type for :order_item violates constraints (1000 (Integer) has invalid type for :amount violates constraints (type?(Float, 1000) failed) failed)
```

**To Reproduce**

types.rb:

```ruby
module Types
  include Dry.Types

  CurrencyOperations = Types::Strict::Symbol
    .constructor(&:to_sym)
    .enum(
      :buy,
      :sell,
    )

  ProductTypes = Types::Strict::Symbol
    .constructor(&:to_sym)
    .enum(
      :currency,
    )
end
```

master_order_builder.rb:

```ruby
class MasterOrderBuilder < Dry::Struct
  attribute :operation, Types::CurrencyOperations
  attribute :product_type, Types::ProductTypes
  attribute :product_id, Types::Integer
  attribute :order_item, Types::Hash.schema(amount: Types::Float)
end
```

**Expected behavior**

I just expect that the follow doesn't throw any error:

```ruby
input = {
  operation: :buy,
  product_type: :currency,
  product_id: 1,
  order_item: {
    amount: 1000
  }
}

MasterOrderBuilder.new(input)
```

**Your environment**

- Ruby version: 2.7.0p0
- Gem version: `gem 'dry-struct', '~> 1.3.0'` (`dry-struct (1.3.0)` is included as dependency).

**Comment by flash-gordon** [comment]
It is expected, in your input `amount` has the type of `Integer`, not `Float`. `include Dry::Types.module` exports nominal types by default, this is why even integer values used to be accepted. This, however, led to confusion and we fixed it by adding `Dry.Types` which exports strict types by default. You can find it mentioned in the changelog https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md#changed-4 
You can fix your issue in a number of ways: explicitly allow integers with `amount: Types::Integer | Types::Float` or coerce all integers to float `Types::Coercible::Float`. Choose what works for you.
