### ISSUE TITLE
Does not create an accessor method when method exists into the mother class

### ISSUE THREAD

**Issue by pyrsmk** [dry-rb/dry-struct#154]
**Describe the bug**

Dry does not create an accessor method when the method already exists into a mother class.

**To Reproduce**

```ruby
class MyService < Dry::Struct
  def foo
    nil
  end
end

class MyChildService < MyService
  attribute :foo, Types::Strict::String
end

# Prints nil
puts MyChildService.new(foo: "foo").foo
```

**Expected behavior**

I expect `MyChildService.foo` to return `"foo"`, because I expect Dry to create the accessor for my attribute even if the method exists into the mother class (but, of course, I don't expect Dry to override my method if it exists into the current class).

**Your environment**

- Affects my production application: NO
- Ruby version: 2.6.5
- OS: OSX

**Comment by flash-gordon** [comment]
No, it's not a bug. The current behavior is expected.

**Comment by solnic** [comment]
@flash-gordon I was actually surprised by this - why is this expected?

**Comment by flash-gordon** [comment]
@solnic because inheritance doesn't matter in this case. There can be different cases, for example including a module with overridden accessor won't work. Or take rom structs where you always define a base struct, you won't be able to override accessors.

**Comment by pyrsmk** [comment]
Is this documented somewhere ?

**Comment by flash-gordon** [comment]
@pyrsmk dunno, I'll take a look. IIRC the reason we did this was rom structs but I'm not entirely sure. But if so, it may be undocumented for this reason (we "added" the feature it to another gem).
