### ISSUE TITLE
Compose transforms

### ISSUE THREAD

**Issue by jamiehodge** [dry-rb/dry-struct#161]
It appears as though `transform_keys` overrides any previously set/inherited proc. It would be nice if they composed.

## Examples

```ruby
class A < Dry::Struct
  transform_keys(&:to_sym)
end

class B < A
  transform_keys(&:underscore)
end

b = B.new('fooBar' => 'baz')
b.foo_bar
```

**Comment by flash-gordon** [comment]
It's not what I had in mind designing dry-struct/dry-types APIs. Every setting _overrides_ prev value. Changing `transform_keys` would not only be a breaking change but would also be in conflict with this idea.
You can override `transform_keys` or add a different method in your code. dry-struct _was_ designed with the idea of custom base struct classes:

```ruby
class MyStruct < Dry::Struct
  def self.transform_keys(proc = nil, &block)
    super((proc || block) >> schema.transform_key)
  end
end

class A < MyStruct
  transform_keys(&:to_sym)

  attribute :foo_bar, 'string'
end

class B < A
  transform_keys { Dry::Core::Inflector.underscore(_1) }
end

b = B.new('fooBar' => 'baz')
b.foo_bar
```

**Comment by jamiehodge** [comment]
Thanks Nikita. I can definitely see how the composition would be surprising (and breaking).
