### ISSUE TITLE
Expanding array item type in generated schema

### ISSUE THREAD

**Issue by davidsevcik** [dry-rb/dry-struct#167]
## Describe the bug

We are using dry-struct to define shape of events and dry-schema for validation of API requests. As the shape of request body is often the same as shape of generated event we would like to stay DRY and reuse the already defined struct. Looking into source code I've discovered I can call `Dry::Struct.schema` which works great until there is an array in the struct definition.

## To Reproduce

```ruby
require 'dry-struct'
require 'dry-types'
require 'dry-schema'

class MyStruct < Dry::Struct
  module T
    include Dry.Types()
  end

  attribute :items, T::Array do
    attribute :value, T::String
  end
end

puts MyStruct.schema
# => #<Dry::Types[Constructor<Schema<keys={items: Constrained<Array<MyStruct::Item> rule=[type?(Array)]>}> fn=Kernel.Hash>]>
puts MyStruct::Item.schema
# => #<Dry::Types[Constructor<Schema<keys={value: Constrained<Nominal<String> rule=[type?(String)]>}> fn=Kernel.Hash>]>

MySchema = Dry::Schema.Params do
  required(:payload).filled(MyStruct.schema)
  # raises /Users/david/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dry-types-1.5.0/lib/dry/types/predicate_inferrer.rb:95:in `public_send': undefined method `visit_struct' for #<Dry::Schema::PredicateInferrer::Compiler:0x00007fb9ee89e0e0> (NoMethodError)
end
```

The reason being that the array item type `Array<MyStruct::Item>` is not expanded into array of struct using its children definition. Have you considered such use case or you think it's not good idea to use dry-struct and dry-schema in this combination? If you agree it should expand the array item definition I'm happy to work on fix but I would appreciate some maintainer to point me to right direction. Thanks.

## My environment

- ruby: 2.7.2
- dry-types: 1.5.0
- dry-schema: 1.6.1
- dry-struct: 1.4.0

**Comment by solnic** [comment]
It should be done the other way around - generate structs from schemas. It's one of the things I've wanted to do for a long time, actually.

**Comment by davidsevcik** [comment]
Hi, 
I've solved it on our end by `Struct#to_dry_schema` method https://github.com/reevoo/realm/blob/master/realm-core/lib/realm/struct.rb I'm sure I've missed some edge cases but it works for us to in combination with our `Contract` class https://github.com/reevoo/realm/blob/master/realm-core/lib/realm/contract.rb

I know that dry-struct documentation discourage from using structs for validation but I believe it can serve nicely as the base (least restrictive) contract and you can tighten restrictions on specific fields as needed. Example:

```ruby
MyStruct = Realm.Struct(foo: Realm::Types::String, bar: Realm::Types::Integer) # base type restrictions

class MyContract < Realm::Contract
  schema MyStruct do
    required(:foo).filled(type?: String, min_size?: 3) # apply additional min_size rule on the foo input value
  end
end

MyContract.new.(foo: 'abc', bar: 1)
```
