### ISSUE TITLE
Struct with optional nested struct requires key in nested struct

### ISSUE THREAD

**Issue by multiplegeorges** [dry-rb/dry-struct#176]
## Describe the bug

I have a parent struct with a nested struct that is optional. The nested struct has one required attribute.

When instantiating the parent struct _without the nested one set_ an error is thrown on an attribute of the nested struct.

## To Reproduce

With code:

```ruby
class Conversion < Dry::Struct
  attribute :conversion_type?, Types::String
  attribute :conversion_date_time, Types::DateTime
end

class Customer < Dry::Struct
  attribute :first_name?, Types::String
  attribute :last_name?, Types::String
  attribute :email?, Types::String

  attribute :conversion?, Conversion
end
```

In REPL:
```
> Customer.new
Dry::Struct::Error: [Conversion.new] :conversion_date_time is missing in Hash input
```

`Customer.new` should work since all attributes are marked as optional.

## Expected behavior

This error should not occur since the struct itself is marked as optional. The enforcement of the presence of the `conversion_date_time` attribute should only occur when the `conversion` attribute of Customer is set.

## My environment

My set of dry gems:

```
    dry-configurable (0.13.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.6)
    dry-container (0.9.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.13, >= 0.13.0)
    dry-core (0.7.1)
      concurrent-ruby (~> 1.0)
    dry-inflector (0.2.1)
    dry-logic (1.2.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.5, >= 0.5)
    dry-struct (1.4.0)
      dry-core (~> 0.5, >= 0.5)
      dry-types (~> 1.5)
      ice_nine (~> 0.11)
    dry-types (1.5.1)
      concurrent-ruby (~> 1.0)
      dry-container (~> 0.3)
      dry-core (~> 0.5, >= 0.5)
      dry-inflector (~> 0.1, >= 0.1.2)
      dry-logic (~> 1.0, >= 1.0.2)
```

**Comment by flash-gordon** [comment]
It's kind of a bug I'd say but I'm not sure if it's easy to fix. dry-struct attempts to build a default value but doesn't really succeed. I need to think a bit more about the fix but you can work around with `Customer.new({})`

**Comment by multiplegeorges** [comment]
Agreed, it's a bit of an edge case. I played with some variations and 

```ruby
  attribute :conversion?, Conversion.optional
```

seems to work.

I'll close the issue, since there seem to be a couple of usable workarounds.

Cheers, and thanks for all the work on the dry-rb group of gems. They are really great.
