### ISSUE TITLE
Wrong class name on site.

### ISSUE THREAD

**Issue by illogikal** [dry-rb/dry-struct#18]
http://dry-rb.org/gems/dry-types/including-types/

class User < Dry::Types::Struct
  attribute :name, Types::String
  attribute :email, Types::Email
  attribute :age, Types::Age
end

Wrong class name (as of latest version).

**Comment by solnic** [comment]
Uhm. Right, docs need to be updated on the website.

**Comment by solnic** [comment]
I added a new section for dry-struct and updated examples in dry-types section to use `Dry::Struct`. This still needs a lot of work though, but at least we don't have outdated docs anymore :) /cc @backus

**Comment by illogikal** [comment]
Just read this. I hope you didn't read my brevity as rudeness, just pointing it out :)
