### ISSUE TITLE
Dry::Struct by including module

### ISSUE THREAD

**Issue by dsisnero** [dry-rb/dry-struct#180]
## A way to construct dry-structs from modules
`
module Dimension
  include Dry::Attributes
  attribute :height, Dry::Types::Float
  attribute :weight, Dry::Types::Float
end

module Part
  include Dry::Attributes
  attribute  :asin, Dry::Types::String
  attribute  :serial , Dry::Types::String
end

class Equipment
  include Dimension
  include Part
end

class Person
  include Dimension
end
`
- Affects my production application: **NO**

**Comment by flash-gordon** [comment]
Pls forward questions or feature requests to our forum https://discourse.dry-rb.org/ (see CONTRIBUTING.md). WRT this one using mixins doesn't look justified IMO.
