### ISSUE TITLE
Warnings for use of undefined @schema and @constructor_type

### ISSUE THREAD

**Issue by mmorga** [dry-rb/dry-struct#19]
This isn't affecting functionality, but it affects the readability of my tests. I'm sending a PR shortly that corrects this.

Thanks for this gem - it really helps a project I'm working on.

**Comment by backus** [comment]
@mmorga which version of dry-struct are you using? My impression was that #7 addressed these warnings

**Comment by solnic** [comment]
Warnings have been fixed. Closing.
