### ISSUE TITLE
Nested attributes of the structure

### ISSUE THREAD

**Issue by nepalez** [dry-rb/dry-struct#2]
Structs in `dry-types` for now do not support nesting like this:

``` ruby
class User < Dry::Types::Struct
  attribute :name, Types::Strict::String

  attribute :profile do
    attribute :email, Types::Coercible::Email # defined somewhere else
    attribute :phone, Types::Coercible::Phone # ^^

    attribute :preferences do
      attribute :food, Types::Array
    end
  end
end

User.new name: 'Joe',
         profile: {
           email: 'joe@doe.com',
           phone: '1(234)567-8900',
           preferences: {
             food: ['ice-cream']
           }
         }
```

I know, that I could define types for preferences and profile explicitly (and I do), but in many cases it doesn't have much sense, because they are parts of only one aggregate.

**Comment by backus** [comment]
If you define the nested structs then it works fine:

```ruby
gem 'dry-types', '~> 0.8.1'
require 'dry/types'

module Types
  include Dry::Types.module

  module Coercible
    # these can be anything I just defined these so I could make your example work
    Email = Types::String
    Phone = Types::String
  end
end

class Preference < Dry::Types::Struct
  attribute :food, Types::Array
end

class Profile < Dry::Types::Struct
  attribute :email, Types::Coercible::Email # defined somewhere else
  attribute :phone, Types::Coercible::Phone # ^^

  attribute :preferences, Preference
end

class User < Dry::Types::Struct
  attribute :name, Types::Strict::String
  attribute :profile, Profile
end

user = User.new(
  name: 'Joe',
  profile: {
    email: 'joe@doe.com',
    phone: '1(234)567-8900',
    preferences: {
      food: ['ice-cream']
    }
  }
)

user # => #<User name="Joe" profile=#<Profile email="joe@doe.com" phone="1(234)567-8900" preferences=#<Preference food=["ice-cream"]>>>
```

**Comment by backus** [comment]
I know you mentioned not wanting to explicitly define these structs but what about just defining them within the class along side the attributes as private constants:

```ruby
gem 'dry-types', '~> 0.8.1'
require 'dry/types'

module Types
  include Dry::Types.module

  module Coercible
    Email = Types::String
    Phone = Types::String
  end
end

class User < Dry::Types::Struct
  class Profile < Dry::Types::Struct
    class Preference < Dry::Types::Struct
      attribute :food, Types::Array
    end
    private_constant(:Preference)

    attribute :email, Types::Coercible::Email # defined somewhere else
    attribute :phone, Types::Coercible::Phone # ^^

    attribute :preferences, Preference
  end
  private_constant(:Profile)

  attribute :name, Types::Strict::String
  attribute :profile, Profile
end

user = User.new(
  name: 'Joe',
  profile: {
    email: 'joe@doe.com',
    phone: '1(234)567-8900',
    preferences: {
      food: ['ice-cream']
    }
  }
)

user # => #<User name="Joe" profile=#<User::Profile email="joe@doe.com" phone="1(234)567-8900" preferences=#<User::Profile::Preference food=["ice-cream"]>>>
```

then the definitions are local to their usage, they can't be reused, but you also don't have to worry about dry-types dynamically constructing anonymous structs for you

**Comment by nepalez** [comment]
@backus Yes, I do it just in a way of your last example. I think it is still a bit overkillish.

I also see the reason we cannot (or should not) implement a "plain" block syntax I gave above. Because the next question I ask myself is... what if I need that nested struct to be optional?

I have no good solution for this, so this is a problem yet, just the proposal for further discussion.

**Comment by Fryie** [comment]
I believe this would be extremely useful, I have a response payload from an API that I want to store as a dry-struct and I think that having to create explicit inner classes for every layer of nesting adds too much overhead for me.

**Comment by flash-gordon** [comment]
this is in master, https://github.com/dry-rb/dry-struct/pull/58

**Comment by Fryie** [comment]
Cool thing! Just to clarify, these three things I'm not sure if they're possible yet:
- Having an array whose elements are an anonymous struct (instead of just a single instance of that element)
- Marking the nested struct as optional
- Supplying a default for the nested struct

otherwise, I could create follow-up issues.

**Comment by flash-gordon** [comment]
We'll unlikely go that far atm, there is `transform_types` for things like this, you also can build your own DSL on top of dry-struct, it's an easy thing to do.
