### ISSUE TITLE
Missing exception for invalid attribute with symbolized constructor type 

### ISSUE THREAD

**Issue by ehannes** [dry-rb/dry-struct#22]
When using constructor type `:symbolized`, I don't get any error messages for invalid attributes. A simple example:

```
module Types
  include Dry::Types.module
end

class User < Dry::Struct
  constructor_type(:symbolized)
  attribute :age, Types::Int.constrained(gt: 18) 
end

User.new(age: 17) 
=> #<User age=17>
```

I'm expecting some kind of error message when I set `age` to `17` in above example. With `constructor_type(:schema)`, it works:

```
class User < Dry::Struct
  constructor_type(:schema)
  attribute :age, Types::Int.constrained(gt: 18) 
end

User.new(age: 17) 
Dry::Struct::Error: [User.new] 17 (Fixnum) has invalid type for :age
```

Is this expected behavior or is this a bug? I'm not quite sure how the different constructor types work. I can't find any documentation other than the discussion in https://github.com/dry-rb/dry-types/issues/72, which I guess might be outdated now when `dry-struct` is a separate gem.

**Comment by backus** [comment]
There isn't great documentation. The best thing I can point you to is the specs in dry-types that more or less break down how the different constructor types work for dry-types: https://github.com/dry-rb/dry-types/blob/d0c60d1bfd6fa3eb743c211d66e78ff2cb51908a/spec/dry/types/hash_spec.rb#L190-L278

**Comment by ehannes** [comment]
@backus Thanks, I'll take a look at the specs. But what about the behavior explained above? Does it work as expected or is it a bug?

**Comment by backus** [comment]
@ehannes well symbolized inherits from the weak schema type which will attempt to perform coercions and silently fallback otherwise. I didn't implement this schema and I don't really agree with it. I just maintained it because @solnic wants to preserve it.

**Comment by solnic** [comment]
We can split it into symbolized_weak and symbolized_strict

**Comment by backus** [comment]
I'm not sure about that actually. I'd rather encourage people to coerce their keys into symbols before passing them in. dry-struct will do some work (depending on the dry types defined for your attributes) to coerce values. I think adding some support for coercing keys though might send the signal that we want to support rich data type handling for keys too when in reality that is a very manual check that the schema types do.

**Comment by solnic** [comment]
I agree in principle, but in reality people would really hate to do that
themselves, they would probably end up deep-symbolizing everything which is
not a great idea. Given how common stringified params/json is and that
everybody wants symbolized keys, making this automated is just pragmatic
and convenient. FWIW this wasn't supported in the early days of dry-v and I
found it to be a PITA to manually symbolize hashes as a separate step.

Anyhow, see you tomorrow :D

**Comment by backus** [comment]
Hm alright I need to think about this then. It feels like we are moving towards constructor types becoming feature flags which is tough. See you tomorrow :P

**Comment by ehannes** [comment]
Thank's for the spec link @backus, that gives a decent overview of the different constructors available. But it does not reveal the difference between `:symbolized` from `:weak` as `:symbolized` includes the same examples as `:weak` does (besides `'yields a special failure if #try is given a non-hash'`, which is only included in `:weak`).

1. To make this gem easier to use, would it be possible to maintain a table in the readme (like the one in https://github.com/dry-rb/dry-types/issues/72) which states how the different constructor types are meant to work?

2. Why does `:symbolized` inherit from `:weak` in the first place? As @solnic says, we are probably talking about _"stringified params/json"_. Is there any reason for the gem to always assume `:weak` typing in that case?

**Comment by backus** [comment]
Sure thing. I'm planning on adding some documentation soon and I'll include a table like in the issue you linked.

**Comment by solnic** [comment]
> Why does :symbolized inherit from :weak in the first place? 

Because the only legitimate usecase is processing input "from the outside", in this case dry-validation should be used, not dry-struct. This hash schema type was added specifically for dry-validation, and any other case where your system digests input that may potentially be broken, in such cases we need `:weak` behavior in order to return partially processed output. ie some values may be valid, others may not, but we want the output back in order to check it, even if it's partially processed due to failures in processing.

Maybe `:symbolized` is a misleading name, because its intention is to not just blindly symbolize all keys, this is *not an equivalent of `Hash#deep_symbolize_keys` monkey-patch from ActiveSupport*. We could consider renaming it to something that describes it better.

ps. sorry for this late reply @ehannes, I was traveling when this issue was reported

**Comment by flash-gordon** [comment]
After the improvements I made (check the changelog when the next release is out) I think this can be closed.
