### ISSUE TITLE
Allow attributes override, or at least constraint

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-struct#27]
In DDD it may be needed to override attribute in a sub-struct. 

For example, I have a `Customer` with optional `#address`, but in `Order` I need `Customer` with mandatory `#address`. 

I have an option to define `class CustomerWithAddress < Customer` with overwritten `#address` attribute, but with current implementation it's impossible to do it. 

Also, we can think about better specific DSL for such things, like `Customer.constrained(required_attribute: :address)`. 
In this case, we need to have ability to revert `.optional` from Dry::Type.

Tell me your idea/opinion, and I can try to make PR.

**Comment by solnic** [comment]
I have mixed feelings about this but it wouldn't be a difficult thing to implement (mostly code removal). WDYT @backus @flash-gordon @timriley ?

**Comment by flash-gordon** [comment]
IIRC we agreed somewhere on the Internet this should be allowed, this is defo not a hard thing to do :)

**Comment by timriley** [comment]
Yeah, I think it would be an expected thing to be able to override an attribute in a subclass.

**Comment by solnic** [comment]
Worth mentioning that right now we violate POLS here, so now I'm thinking we should do this

**Comment by flash-gordon** [comment]
I'll send a PR

**Comment by backus** [comment]
Interesting. In our private codebase that uses `dry-struct` we also ended up with some models named `FooWithBar` for somewhat different reasons. We more or less grew to view it as an anti-pattern and implemented a new abstraction outside of `dry-struct` to address this.

**Comment by backus** [comment]
It might be nice to require the dry-struct user to be explicit about the cases where they want to do this. In other words, instead of

```ruby
class Customer < Dry::Struct
  attribute 'address', Dry::Types['address'].optional
end

class CustomerWithAddress < Customer
  attribute 'address', Dry::Types['address']
end
```

what if the method here was

```ruby
class CustomerWithAddress < Customer
  redefine_attribute 'address', Dry::Types['address']
end
```

I think this would be nice

**Comment by solnic** [comment]
> We more or less grew to view it as an anti-pattern and implemented a new abstraction outside of dry-struct to address this.

@backus could you tell a bit more? I never liked structs like `User` and then `UserWithAddress` (although I had cases where coming up with a nice and meaningful name was really simple)

**Comment by backus** [comment]
Well we don't use ROM so at first our queries would have to return a model that properly fit the data being returned. Therefore, initially, we had to create one-off models that would specify the exact relationship being returned for each query. Now we do something more dynamic depending on the data returned by the query. I can give more context if that is helpful, but the problem in our case I think was just that we are using dry-struct only and no ORM along with it

**Comment by solnic** [comment]
@backus so sounds like you built something similar to rom-repository, it builds structs dynamically based on relation schemas (dry-struct under the hood!)

**Comment by backus** [comment]
Maybe. I'm not sure how much `ROM::Repository` does. This is basically a specialized delegation wrapper that doesn't abuse `method_missing`.

```ruby
class App
  class Relationship
    include Concord.new(:primary_model, :included_models)

    def initialize(primary_model, **included_models)
      super(primary_model, included_models)

      delegate_to_model
      delegate_to_included
    end

    private

    def delegate_to_model
      model_methods.each do |method_name|
        define_singleton_method(method_name, &primary_model.method(method_name))
      end
    end

    def model_methods
      primary_model.public_methods - Dry::Struct::Value.public_instance_methods
    end

    def delegate_to_included
      included_models.each { |name, model| define_singleton_method(name) { model } }
    end
  end
end
```

Usage is like

```ruby
customer = App::Relationship.new(
  customer_data,
  address: address_data,
  name:    name_data,
  order:   order_data
)
```

where the behavior is

| via Relationship                 | Delegation                   |
| :-----------------               | :-----------                 |
| `customer.id`                    | `customer_data.id`           |
| `customer.address.street1`       | `address_data.street1`       |
| `customer.name.first`            | `name_data.first`            |
| `customer.order.tracking_number` | `order_data.tracking_number` |

It is pretty helpful. I'm sure ROM::Repository does way more.

**Comment by solnic** [comment]
@backus that's pretty clean, given the amount of dynamic behavior :)

> I'm sure ROM::Repository does way more.

It does, but it uses dry-rb gems so a ton of complexity is handled by these gems, which made implementing pretty advanced features in rom really simple. Repositories automatically map relation tuples, including tuples from composed relations, into structs or struct aggregates. You can project data however you like and repos will always know what kind of structs it needs to create. They are cached so classes are created only once for every unique relation.

If you dump a relation into ast you'll see things that should look familiar:

``` ruby
[6] pry(main)> repo.users.to_ast
=> [:relation,
 [:users,
  {:dataset=>:users},
  [:header,
   [[:attribute, #<ROM::SQL::Type[Integer] primary_key=true name=:id source=ROM::Relation::Name(users)>], [:attribute, #<ROM::SQL::Type[NilClass | String] name=:name source=ROM::Relation::Name(users)>]]]]]
```

and a composed relation:

``` ruby
[8] pry(main)> repo.aggregate(:tasks).to_ast
=> [:relation,
 [:users,
  {:dataset=>:users},
  [:header,
   [[:attribute, #<ROM::SQL::Type[Integer] primary_key=true name=:id source=ROM::Relation::Name(users)>],
    [:attribute, #<ROM::SQL::Type[NilClass | String] name=:name source=ROM::Relation::Name(users)>],
    [:relation,
     [:tasks,
      {:keys=>{:id=>:user_id}, :combine_type=>:many, :combine_name=>:tasks, :dataset=>:tasks},
      [:header,
       [[:attribute, #<ROM::SQL::Type[Integer] primary_key=true name=:id source=ROM::Relation::Name(tasks) qualified=true sql_expr=#<Sequel::SQL::QualifiedIdentifier @table=>"tasks", @column=>"id">>],
        [:attribute,
         #<ROM::SQL::Type[Integer] foreign_key=true target=:users name=:user_id source=ROM::Relation::Name(tasks) qualified=true sql_expr=#<Sequel::SQL::QualifiedIdentifier @table=>"tasks", @column=>"user_id">>],
        [:attribute, #<ROM::SQL::Type[NilClass | String] name=:title source=ROM::Relation::Name(tasks) qualified=true sql_expr=#<Sequel::SQL::QualifiedIdentifier @table=>"tasks", @column=>"title">>]]]]]]]]]
```

All these attributes are backed by dry-types with extended API for rom-sql :)

**Comment by backus** [comment]
Jeez that is pretty neat. Maybe I need to give ROM another look for this project soon.

**Comment by solnic** [comment]
@backus we're about to release rom 3.0.0 rom-sql 1.0.0 and rom-repository 1.0.0, so it's gonna be a really good time to check it out :)

**Comment by Kukunin** [comment]
Just an idea: that while it may be too powerful and dangerous to allow arbitrary type redefine, 

some DSL for type extension would be neat.

```ruby
class A < Dry::Struct
  attribute :attr, Types::Strict::String
end

class B < A
  extend_attribute :attr, &:optional
end
```

Actually, having opposite modifier to cancel `.optional` (`.required`?) along with such ability would cover 95% of use cases. 

Can you imagine other need to redefine attribute other than make it required?

P.S. I understand that this idea is much harder to implement, so consider as just one more opinion =)

**Comment by Kukunin** [comment]
@solnic also, can I kindly ask to take a look into this issue, as it's crucial in DDD modelling and helpful, at least for us =)

**Comment by backus** [comment]
> > Jeez that is pretty neat. Maybe I need to give ROM another look for this project soon.
>
> @backus we're about to release rom 3.0.0 rom-sql 1.0.0 and rom-repository 1.0.0, so it's gonna be a really good time to check it out :)

As a followup, we are about to add ROM to our primary codebase :smile:

**Comment by solnic** [comment]
@backus oh wow that's fantastic! ping me if you need any help
