### ISSUE TITLE
inconsistent behavior when combining default and constructor

### ISSUE THREAD

**Issue by Incanus3** [dry-rb/dry-struct#30]
dry-struct behaves inconsistently when there is an attribute with both `default` and `constructor`. Using `constructor_type :schema`, if you don't specify value for the attribute, the default is used and is run through the constructor, but if you specify `nil` as the attribute value, the default is still used, but is NOT run through the constructor. I think it may be open to discussion whether the defaults should be run through the constructor (for me it makes sense to do it), but I don't think it's right to run them through in one case and not in the other.

I've created a spec for this behavior [here](https://gist.github.com/Incanus3/24f87857504021642d312e189a3fdfcc).

**Comment by flash-gordon** [comment]
I agree this maybe a bit surprising, but it's up to the user to provide a _valid_ value in the default block. However, it will stay like this and should be documented.

@solnic what do you think if we add a second argument to the default block? E.g.
```ruby
RoundTime = Types::Time.constructor(&:round)
RoundTime.default { |value, type| type[Time.now] } 
```

**Comment by solnic** [comment]
@flash-gordon not a bad idea

**Comment by flash-gordon** [comment]
hell, why did I call that "second"?
Anyway, support for `RoundTime.default { |type| type[Time.now] }` was added to `dry-types` (currently in master), we need to update the docs
