### ISSUE TITLE
Dry::Struct::Value no longer works in 0.2.0

### ISSUE THREAD

**Issue by dgollahon** [dry-rb/dry-struct#31]
```ruby
class Foo < Dry::Struct::Value
  attribute :bar, Dry::Types['strict.string']
end
```

results in

```
TypeError: no implicit conversion of nil into Hash
from /Users/gollahon/.rvm/gems/ruby-2.4.0/gems/dry-struct-0.2.0/lib/dry/struct/class_interface.rb:70:in `merge'
```

Seems like [here](https://github.com/dry-rb/dry-struct/blob/master/lib/dry/struct/class_interface.rb#L70) `@schema` happens to be `nil`.

Incidentally,

```ruby
class Baz < Dry::Struct
  attribute :qux, Dry::Types['strict.string']
end
```

works fine.

**Comment by flash-gordon** [comment]
@dgollahon thanks for reporting this! It was not trivial to find out why the specs were passing :) We'll push a release as soon as Travis verifies my changes

**Comment by flash-gordon** [comment]
0.2.1 is on rubygems

**Comment by dgollahon** [comment]
@flash-gordon: Glad the report was helpful. Thanks for fixing it quickly!
