### ISSUE TITLE
Attribute :id has already been defined

### ISSUE THREAD

**Issue by FlorianDoublet** [dry-rb/dry-struct#35]
Hi, when I launch my worker, an error append with Dry-struct : 
`Dry::Struct::RepeatedAttributeError: Attribute :id has already been defined`

But nobody can reproduce this bug.

**Comment by flash-gordon** [comment]
It looks like you're loading the class twice, that's why this might happen. Also I see there is `AS::Dependencies` in the trace and I wouldn't recommend to load dry-* dependencies with `activesupport`, try to load them once on application startup instead so that AS won't reload them

**Comment by FlorianDoublet** [comment]
In fact I run my rails server, and then I launch my worker with the command `rake resque:work QUEUE='*'`. I don't know how to load them just once, can you tell me how to do it ?

**Comment by flash-gordon** [comment]
This usually means moving stuff to the `lib` directory and requiring it in a initializer.

**Comment by guizmaii** [comment]
Hi,

I work with @FlorianDoublet.
It seems that just add the following line in the `application.conf` file is enough to fix the problem:
`config.eager_load_paths += Dir[ Rails.root.join('app', 'dir_that_contains_the_types', '**/') ]`

Thanks for your help
