### ISSUE TITLE
A way to define high-level constraints

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-struct#39]
There are situations, where domain entity should implement an invariant, that can't be expressed with DRY types (or overhead of such expressing is too high). 

For instance, when my contact person might have *an email* and *a phone*, but at least one attribute should be set. Or, when I have two entities, and I need a rule for first entity based on second. 

Current way is to override constructor, such as 

```ruby
    def initialize(params)
      error_message = 'at least :email or :phone should be in Hash input'
      raise Dry::Struct::Error, error_message unless params[:email] || params[:phone]

      super(params)
    end
```

It has downfalls: it calls so early, and any bad input may cause a crash within this code. Also, it's not pretty way. I suspect, there is not always a hash as argument, a different dry-struct might be passed as well.

Another possible solution is to override `#input`, but that's hard and fragile as well.

The best solution is to have some ability to set callback **after** dry-struct is initialized and all internal checks are passed, but **before** illegal object is initialized and returned to a callee. Something like

```ruby
class ContactPerson < Dry::Struct
  validate -> (instance) { instance.name || instance.email }
end
```

By default, it's `validate -> (_) { true }`

**Comment by kbacha** [comment]
I would like to see something like this implemented. In reality, I'd like to be able to replace or amend the hash schema with additional predicates:
```ruby
class SomeStruct < Dry::Struct::Value
  predicates do
    required(:name).filled
    required(:email).filled(format?: EMAIL_REGEX)
    required(:age).maybe(:int?)
  end
  attribute :name, Types::String
  attribute :email, Types::String
  attribute :age, Types::Int

**Comment by Kukunin** [comment]
I don't think predicates are helpful - everything you can implement with `dry-types` itself, e.g. 

    Email = Types::String.constrained(format: EMAIL_REGEX)
    attribute :email, Email

It also improves reusability and reveals intention better.

What I'm talking in this issue is analog of high-level rules from `dry-validation` into `dry-struct`. 
AFAIK, those are considered as different concepts, and even separate gems will be introduced

**Comment by solnic** [comment]
At this point, we're not going to add anything like that. You can experiment with some kind of an extension and once it's working and provides clear value, please describe your experience in a thread on discourse.dry-rb.org and then we may consider adding something similar to dry-struct.
