### ISSUE TITLE
Array elements are shared between instances

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [dry-rb/dry-struct#43]
Objects with an array attribute sometimes share the same elements of this array. If the objects have other attributes like `id`, then the elements are shared. If not, the elements aren't shared.

Use the following example to reproduce the behaviour.

```ruby
# types.rb

require "dry-types"

module Foo
  module Types
    include Dry::Types.module
  end
end

```

```ruby
# test.rb

require "dry-struct"

require "foo/types"

module Foo
  class Test  < Dry::Struct
    constructor_type :strict_with_defaults

    # Works if, :id attribute isn't present
    # attribute :id,     Types::Coercible::Int

    # Fails if, :id attribute is present
    attribute :id,     Types::Coercible::Int
    attribute :linked, Types::Strict::Array.member(Test).default([])
  end
end
```

```ruby
# test_spec.rb

require "spec_helper"

require "foo/test"

module Foo
  describe Test do
    describe "initialization" do

      let(:a) { described_class.new(id: 4) }
      let(:b) { described_class.new(id: 5) }

      # works
      # let(:a) { described_class.new() }
      # let(:b) { described_class.new() }

      it "works only without id attribute" do
        expect(a.linked).to eq []
        expect(b.linked).to eq []

        a.linked.push(b)
        puts "schema: #{a.class.schema}"

        expect(a.linked).to eq [b]
        expect(b.linked).to eq []
      end
    end
  end
end
```

The `value` field in the `a.class.schema` changes between the execution of the two cases.

Maybe this issue is related to #2.

I'm not sure what the expected behaviour is. Is it allowed to change an array (add/remove elements) after initialization?

**Comment by flash-gordon** [comment]
Please check out this PR https://github.com/dry-rb/dry-rb.org/pull/166/files
Types share default values and if you're intent on changing the value after initialization you must wrap it with a block `.default { [] }`. I'll update dry-types docs soon

**Comment by ThomasKoppensteiner** [comment]
@flash-gordon thank you for your fast response. Yes wrapping the default value in a block helps. I'll close the issue.

For those who read this later. The above PR closes this issue: https://github.com/dry-rb/dry-rb.org/issues/155
