### ISSUE TITLE
Introspective Functions / Testing?

### ISSUE THREAD

**Issue by MissingHandle** [dry-rb/dry-struct#45]
I'm browsing the source, seems like some introspective methods would be useful for testing.  In defining a Dry::Struct, and wanting to write unit tests that I have defined them as expected, 

I'm writing the following:

```
      class BaseStruct < Dry::Struct

        def self.includes_attribute?(attr)
          attr_names.include?(attr.to_sym)
        end

        def self.attr_names
          # schema part of Dry::Struct
          @attr_names ||= schema.keys
        end
       
        ...
```

seems like methods like these would be useful within Dry::Struct itself?

**Comment by MissingHandle** [comment]
Also - any thoughts on shoulda-like helpers - 

```
expect(SomeStruct).to have_attribute(:attr_name).of_type(SomeType)
```

would this be desirable? or do you have other thoughts?

ftr, willing to contribute if desired.

**Comment by AMHOL** [comment]
@MissingHandle check out [rspec-dry-struct](https://github.com/matic-insurance/rspec-dry-struct), I think this does exactly what you want.

**Comment by MissingHandle** [comment]
Ah - thanks @AMHOL ! That indeed takes care of the testing need.  

What about the introspective functions - any thoughts there? I'm coming across a scenario where I have a specification in a JSON file. Within my code, I want to make sure that values in the JSON are valid according to various structs i've defined. For me, the introspective functions seem unavoidably necessary - would you want them within dry-struct?

**Comment by flash-gordon** [comment]
@MissingHandle `Struct.attribute?` and `Struct.attribute_names` have landed in master :) I'll  push a new release next week

**Comment by solnic** [comment]
I'd actually suggest moving it to an optional module. This type of
functionality shouldn't be typically needed at runtime. I would even say
this should be a rare case that somebody needs this for testing. It's much
better to test behavior versus configuration of some classes.

**Comment by flash-gordon** [comment]
@solnic tbh I added this specifically for use at the runtime. FWIW using `attribute?` is more semantic-full than a plain `respond_to?` call and `attribute_names` can be useful for metaprogramming. I wouldn't write a test for a struct, for my taste, it's a waste of time :)

**Comment by MissingHandle** [comment]
I also wanted the functions for runtime. Though I was asking about it, I might agree with you on the testing.
