### ISSUE TITLE
Violated constraint error message looks irrelevant

### ISSUE THREAD

**Issue by mvasin** [dry-rb/dry-struct#46]
Here's a class:
```ruby
class ConstrainedUser < Dry::Struct
  attribute :name, Types::Strict::String
  attribute :age,  Types::Strict::Int.constrained(gteq: 18)
end
```
Here's the violated constraint error message:
```
[1] pry(main)> user = ConstrainedUser.new(name: 'Sally', age: 17)
Dry::Struct::Error: [ConstrainedUser.new] 17 (Integer) has invalid type for :age
from /Users/mvasin/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/dry-struct-0.3.0/lib/dry/struct/class_interface.rb:109:in `rescue in new'
```

The 'invalid type' error message looks weird, as 17 is a perfectly valid Integer.

At the same time, `dry-types` part looks fine:

```
[2] pry(main)> Types::Strict::Int.constrained(gteq: 18)[17]
Dry::Types::ConstraintError: 17 violates constraints (gteq?(18, 17) failed)
from /Users/mvasin/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/dry-types-0.10.3/lib/dry/types/constrained.rb:28:in `block in call'
```
I understand that a violated constraint type value is an invalid type value, so overall the error message is not wrong, but should be more specific.

**Comment by solnic** [comment]
Detailed exception messages from attribute types don't bubble up yet, that's why you get a generic message, the underlying exception does include details about which predicate failed.

**Comment by smakagon** [comment]
@solnic seems like it's not a problem with the dry-struct (0.3.1) ?
I've just tried to reproduce the issue, but I see this nice error message:

```
gems/ruby-2.4.0@dry-playground/gems/dry-struct-0.3.1/lib/dry/struct/class_interface.rb:94:in `rescue in new': 
[User.new] 17 (Integer) has invalid type for :age violates constraints (gteq?(18, 17) failed) (Dry::Struct::Error)
```
Which is displaying violated constraints.

**Comment by flash-gordon** [comment]
@smakagon ahh, right, this was fixed in https://github.com/dry-rb/dry-types/commit/a19ea94312c1e7d2d0dc5a54bcfec3320f42548d
