### ISSUE TITLE
Use meta on self defined objects

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-struct#47]
_From @lal-s on August 18, 2017 15:18_

I want to add meta data to my attributes. For example, I have the following classes: 

```ruby
class User < Dry::Struct
  attribute :name, Types::String.meta(my_meta: 'meta'
  attribute :address, Address
  attribute :accounts, Types::Array.member(Account).meta(resource: 'my resource')
end

class Address < Dry::Struct
  attribute :street, Types::String
  attribute :city, Types::String
end

class Account < Dry::Struct
  attribute :account_num, Types::Int
end
```
 I want to be able to add meta data to attribute `address` in `User`, is there  a way to do it?
i.e

```ruby
attribute :address, Address.meta(my_meta: 'meta')
```

Probably if I can define it differently eg: `attribute :address, Types::Address.meta(my_meta: 'meta')` just so that it lets me use meta on it.

_Copied from original issue: dry-rb/dry-types#209_

**Comment by solnic** [comment]
@lal-s seems like we forgot to add this method to dry-struct

**Comment by flash-gordon** [comment]
@solnic we didn't. Adding meta requires copying the class with new options. If you do it with inheritance you get this behavior
```ruby
class User < Dry::Struct
  attribute :name, Types::Strict::String
end

UserWithMeta = User.meta(foo: :bar)

UserWithMeta.new(name: 'Jade') == User.new(name: 'Jade') # => false
```
@solnic does it look expected to you?

We could some sort of proxy object but this would look strange a bit too
```ruby
UserWithMeta = User.meta(foo: :bar)
UserWithMeta.is_a?(Class) # => false
```

**Comment by solnic** [comment]
> @solnic does it look expected to you?

Yes it does, because a class with meta information is, indeed, different than the one without meta.

**Comment by lal-s** [comment]
Thank you for the reply. or is it possible to add something like member to `Type::Class`, so that I can use meta on it

Something like this or by using any other built in dry-types:

```
class User < Dry::Struct
  attribute :name, Types::String.meta(my_meta: 'meta'
  attribute :address, Type::Class.member(Address).meta(my_meta: 'my_meta')
  attribute :accounts, Types::Array.member(Account).meta(resource: 'my resource')
end
```

My use case is just to have the type as the Class with meta data on it.

**Comment by lal-s** [comment]
I am interested in addressing this issue. Can I get more information regarding your perspective on the solution to the problem.

**Comment by GustavoCaso** [comment]
@solnic @flash-gordon do you still wants to add `meta` information in the attributes ?
