### ISSUE TITLE
Proposal: Dry::Struct.map

### ISSUE THREAD

**Issue by serradura** [dry-rb/dry-struct#49]
First of all, https://discuss.dry-rb.org/ is down.

A little pattern appeared in my code base. Have to map a collection's items to Dry::Struct objects.

So, I did a module to extend my structs and share this new feature. But in my opinion, I think this could be a common problem and we can add this new little feature to the project.

PS: Another cool feature related to this one is: create another method (or a flag to `Dry::Struct.map`) to symbolize string Hash keys.

**Comment by ifokeev** [comment]
https://github.com/dry-rb/dry-struct/issues/49

**Comment by flash-gordon** [comment]
sorry, I don't get what this method supposed to do. @serradura could you elaborate on this?

**Comment by flash-gordon** [comment]
Discourse is at https://discourse.dry-rb.org/, I updated the links in CONTRIBUTING.md
For mapping you can go with the `Array` type, i.e. 
```ruby
array_type = Types.Array(MyStruct)
array_type.(data[:raw_hashes])
```
For key transformations see https://github.com/dry-rb/dry-struct/pull/64
