### ISSUE TITLE
No error raises when invalid data is use

### ISSUE THREAD

**Issue by GustavoCaso** [dry-rb/dry-struct#52]
I know from the guides that encourage not to use `symbolize` or `weak` with `dry-struct` but I was looking into other issue with `dry-types` and the example in the issue looks like it should raise an exception.

```ruby
module TestTypes
  include Dry::Types.module
end

 module Test
   class Fail < Dry::Struct
      constructor_type :symbolized
      attribute :age, TestTypes::Strict::Int
   end
 end

value = Test::Fail.new("age" => "2.2") #=> <Test::Fail age="2.2">
```

Looks like the error could be in `dry-types`

**Comment by solnic** [comment]
No it should not raise, structs shouldn't use symbolized constructors as it's designed for parsing potentially invalid input in cases like data validation.
