### ISSUE TITLE
Incorrect behaviour of .attribute_names class method

### ISSUE THREAD

**Issue by 0exp** [dry-rb/dry-struct#57]
Suppose we have a simple struct and we want to receive the list of attribute names:

```ruby
class User < Dry::Struct
  attribute :name, Dry::Types::Any
  attribute :age, Dry::Types::Any
end

User.attribute_names # => [:name, :age]
```

If you continue to work with this structure after .attribute_names call, the following call of .attribute_names will return the cached value

```ruby
# Reopen and define new attributes (after .attribute_names call):
class User
  attribute :email, Dry::Types::Any
  attribute :id, Dry::Types::Any
end

# Current (incorrect):
User.attribute_names # => [:name, :age]

# Expected:
# User.attribute_names # => [:name, :age, :email, :id]
```

The problem is here:
https://github.com/dry-rb/dry-struct/blob/master/lib/dry/struct/class_interface.rb#L206

```ruby
module Dry::Struct::ClassInterface
...

  # Gets the list of attribute names
  #
  # @return [Array<Symbol>]
  def attribute_names
    @attribute_names ||= schema.keys # here
  end
  
...
end
```

Is it really need to cache schema's keys (object with dynamic behaviour)?

**Comment by flash-gordon** [comment]
I would argue defining attributes in different places is a smell but it's just a bug after all and we need to reset the cache on adding new attributes.
