### ISSUE TITLE
`#[]` vs public_send "regression"

### ISSUE THREAD

**Issue by paul** [dry-rb/dry-struct#69]
I originally added this as a comment on #66, but I'm also opening an issue so its seen.

Turns out, I was relying on the `#public_send` behavior of `#[]` for a project of mine. I'm using Dry::Struct to write a presenter library, and I was using it with Rails to generate urls. I had a superclass like this:

```ruby
class Presenter < Dry::Struct
  transform_types { |t| t.meta(omittable: true) }
  attribute :url, Types::Url

  def url
    url_for(self)
  end
end
```

Then, subclasses could either override that method themselves, or when one presenter is calling another it could be passed in if needed, in case of nested routes.

```ruby
class WidgetCollection < Presenter
  attribute :user_id, Types::Integer
  attribute :widgets, Types::Array

  def url
    user_widgets_path(user_id)
  end

  def widgets
    @widgets.map { |widget| WidgetPresenter.new(widget: widget, url: widget_path(user_id: user_id, widget) }
  end
end
```

Because it now uses `#fetch` instead of `#public_send`, I can no longer access "attributes" that are overridden by explicit methods. I also cannot use `Types::URL.default { }` because that block is eval'd in the class context rather than the instance (`undefined method 'url_for' for Presenter:Class`).

What I ended up doing is just redefining the `#[]` method to use `#public_send` in my Presenter superclass, so its not that big a deal.

**Comment by flash-gordon** [comment]
Yeah, we aware of it, this will be mentioned in the changelog.
