### ISSUE TITLE
Struct gets coerced into **kwargs (when *args is also present)

### ISSUE THREAD

**Issue by sevos** [dry-rb/dry-struct#80]
Why would we ever define `Dry::Struct#to_hash` method? Its purposed for implicit coercions like in the following example. We should define `#to_h` only, I guess.

Example:

```
[1] pry(main)> HueBridge.new.lights.last
=> #<HueBridge::Light id=15 name="Sofa" on=true brightness=144 hue=7676 saturation=199>
[2] pry(main)> a = HueBridge.new.lights.last
=> #<HueBridge::Light id=15 name="Sofa" on=true brightness=144 hue=7676 saturation=199>
[3] pry(main)> def b(*c, **d)
[3] pry(main)*   puts "args"
[3] pry(main)*   p c
[3] pry(main)*   puts "kwargs"
[3] pry(main)*   puts d
[3] pry(main)* end
=> :b
[4] pry(main)> b(1, a)
args
[1]
kwargs
{:id=>15, :name=>"Sofa", :on=>true, :brightness=>144, :hue=>7676, :saturation=>199}
=> nil
[5] pry(main)> b(a, 1)
args
[#<HueBridge::Light id=15 name="Sofa" on=true brightness=144 hue=7676 saturation=199>, 1]
kwargs
{}
=> nil
```

**Comment by sevos** [comment]
Monkey-patch fix:

```ruby
class Dry::Struct
  undef_method :to_hash

  def to_h
    self.class.schema.keys.each_with_object({}) do |key, result|
      result[key] = Hashify[self[key]]
    end
  end
end
```

But I am not 100% of the implications of it

**Comment by flash-gordon** [comment]
Yeah, I know that, this is how ruby works, they really messed with it IMO. Structs are supposed to work as hashes so this is expected. I wouldn't go with a monkey patch though, you can subclass `Dry::Struct` and use it as a base where you need

```ruby
class MyStruct < Dry::Struct
  undef_method :to_hash
end
```
^also, you don't need to override `to_h`, undefining of `to_hash` doesn't affect it.

**Comment by sevos** [comment]
You say "Structs are supposed to work as hashes", but I wonder where is this requirement coming from.

In Ruby neither `Struct` nor `OpenStruct` implements the implicit conversion method `to_hash`. Both implement the explicit conversion method `#to_h`
More on the differences between implicit and explicit conversion methods [here](https://zverok.github.io/blog/2016-01-18-implicit-vs-expicit.html).


```
irb(main):001:0> A = Struct.new(:a, :b)
=> A
irb(main):002:0> def iii(**kwargs)
irb(main):003:1> puts kwargs
irb(main):004:1> end
=> :iii
irb(main):005:0> iii A.new(1,2)
Traceback (most recent call last):
        3: from /Users/sevos/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        2: from (irb):5
        1: from (irb):2:in `iii'
ArgumentError (wrong number of arguments (given 1, expected 0))
irb(main):006:0> iii A.new(1,2).to_h
{:a=>1, :b=>2}
=> nil
irb(main):009:0> iii OpenStruct.new(a: 1, b: 2)
Traceback (most recent call last):
        3: from /Users/sevos/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        2: from (irb):9
        1: from (irb):2:in `iii'
irb(main):010:0> iii OpenStruct.new(a: 1, b: 2).to_h
{:a=>1, :b=>2}
=> nil
irb(main):007:0>
```

I am afraid that there may be more cases when the struct may be deconstructed into a hash prematurely or accidentally causing us to lose the information about the type of the data it carries. Please tell me what are the cases you find this behaviour useful? Maybe there is really more good than harm...
Personally I use `Dry::Struct` as a base class for business domain entities and it's more of a better-Struct than a better-Hash, so I would prefer not to deconstruct that objects easily. Of course there should be a way to convert it to a hash, when needed.

Thanks for the idea for the base class, but now I worry more about dry-struct compatibility with other libraries, which may deconstruct it accidentally.

**Comment by flash-gordon** [comment]
This is not a requirement, this is a design choice. One quick example is `rom`'s interface for writing data, it relies on coercions made by `Hash[value]`, anything hash-like can be passed in, including structs.

**Comment by sevos** [comment]
Thanks for clarification

**Comment by abrthel** [comment]
For the record, this also just bit me. I was definitely not expecting my entity object to deconstruct into a hash because I had a keyword arg in a composite class initializer.

**Comment by kke** [comment]
FYI: This does not even require `**kwargs`, regular keyword arguments are enough.

```
def display(*items, color: true)
  puts "items: %p color: %p" % [items, color]
end
```

Calling this with a `Dry::Struct` causes: `ArgumentError : unknown keywords: item_attribute, item_attribute2, item_attribute_x`
