### ISSUE TITLE
How to return an object in json to be a hash and not a string hash

### ISSUE THREAD

**Issue by cyb-ahmadh** [dry-rb/dry-struct#81]
I have a response from an api like this 

```
{
    "total": 59198,
    "products": [
        {
            "id": "23423",
            "name": {
                "German": "s.Oliver BLACK LABE - Damen, Weiß, Größe 44"
            },
            "brand": "s.Oliver BLACK LABEL",
            "image_url": "https://some_url.com",
            "category": "Shirts & Tops"
        },...
   ]
}
```

so i have written a class which is like this:

```
  class SomeService < Dry::Struct
    include Dry::Types.module

    attribute 'id',        String
    attribute 'brand',     String
    attribute 'image_url', String
    attribute 'category',  String
    attribute 'name',      Strict::Hash
  end
```
But this is returning the `name` object as `string`

```
{
        "brand": "s.Oliver BLACK LABEL",
        "name": "{\"German\"=>\"s.Oliver BLACK LABEL - Damen, Weiß, Größe 44\"}"
}
```

Any ideas how to do it ?

**Comment by solnic** [comment]
We're using issues for bugs and confirmed feature requests. Please read CONTRIBUTING in this project's repository to learn more.

**Comment by cyb-ahmadh** [comment]
Ok. Let me know where i can ask questions based on this gem since this gem doesn’t have much or no presence on stackoverflow. And this gem doesn’t have extensive guide or examples. So let me know. Thanks

**Comment by flash-gordon** [comment]
Here you are https://github.com/dry-rb/dry-struct/blob/master/CONTRIBUTING.md
GH shows you a link when you're creating an issue for the first time
<img width="351" alt="image" src="https://user-images.githubusercontent.com/802486/37423991-5ee741fa-27d0-11e8-9f9e-f898e966aa66.png">

**Comment by cyb-ahmadh** [comment]
@flash-gordon Yes i know that and i had seen that particular message box as well. My question was different. I just wanted some help since i did not find a suitable place for asking and the reason i mentioned above. But its ok. Thanks for the great gem but please update your documentation with good examples. Nothing more. Thanks :)

**Comment by timriley** [comment]
The suitable place for asking is in https://discourse.dry-rb.org, as mentioned in the linked contributing guidelines.
