### ISSUE TITLE
Constructor should delegate to original struct

### ISSUE THREAD

**Issue by abrthel** [dry-rb/dry-struct#82]
`dry-struct v3.1`

I ran into an issue where creating a Type with a custom constructor would result in:

`#<NoMethodError: undefined method 'default?' for #<Dry::Struct::Constructor type=Helios::SlotTemplateKey>>`

when trying create instances of my other dry-struct entities that depend on the type with the custom constructor.

I believe a valid solution to this case would be for the new Dry::Struct::Constructor instance to delegate any incoming calls to the original struct type. Something along the lines of the solution below.

```ruby
    class Dry::Struct::Constructor
      def method_missing(method, *args)
        if type.respond_to?(method)
          self.class.send(:define_method, method) do |*args|
            type.send(method, *args)
          end
          send(method, *args)
        else
          super
        end
      end
      
      def respond_to_missing?(method, private=false)
        type.respond_to?(method, private) || super
      end
    end
```

**Comment by flash-gordon** [comment]
Yeah, it should work somewhat similar to `dry-types` I guess, we'll fix this, eventually
