### ISSUE TITLE
Schema constructor_type gives you implicit nil defaults

### ISSUE THREAD

**Issue by faucct** [dry-rb/dry-struct#85]
```ruby
require 'dry/struct'

class Foo < Dry::Struct
  constructor_type :schema

  Types = Dry::Types.module
  attribute :bar, Types::Strict::Bool
end

p Foo.new({}).bar
# => nil
```

I expect this code to fail with missing key as I have provided no default for `#bar` and `nil` is definitely not `Types::Strict::Bool`.

**Comment by flash-gordon** [comment]
This is expected behavior, sort of. And it's also confusing, we aware of it. TL;DR constructor_types will be removed in the next version, see [CHANGELOG](https://github.com/dry-rb/dry-struct/blob/7b2b22c5d71652edeb97c358bee5110d331ff87d/CHANGELOG.md).
