### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by jpaulgs** [dry-rb/dry-struct#86]
Hi,

Sorry I would have asked this on gitter chat but it just wasn't workign for me.

I'd like to use the nested attributes that are available on master but a yet in a tagged release.  Is there a release scheduled?

**Comment by flash-gordon** [comment]
There is no such thing, but I hope I’ll be able to push new versions of dry-types and dry-struct later this week, the only blocker so far is docs. Fortunately, it’s nearly complete.

**Comment by flash-gordon** [comment]
New versions have been pushed
