### ISSUE TITLE
#new not working with transform_types

### ISSUE THREAD

**Issue by lister** [dry-rb/dry-struct#88]
I'm not sure if I'm using `transform_types` correctly. 

I want to do some type transformations on an array on initalization and later use `#new` to create a copy of the struct, but I couldn't get this to work. Am I doing it wrong? It seems to work as expected without `transform_type`.

Please let me know if you need more information or if my question is not clear to you. Please find the code and the output below.

Cheers, Simon

```ruby
# running ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"
  gem "dry-struct", "0.5.0"
end

module Types
  include Dry::Types.module
end

class Tag < Dry::Struct
  transform_keys(&:to_sym)
  attribute :name, Types::Strict::String
end

class EntityWorking < Dry::Struct
  transform_keys(&:to_sym)

  attribute :name, Types::Strict::String
  attribute :tags, Types::Strict::Array.of(Tag)
end

class EntityFailing < Dry::Struct
  transform_keys(&:to_sym)

  transform_types do |type, name|
    case name
    when :tags then type.constructor do |tags|
      tags.map { |t| Tag.new(name: t) }
    end
    else
      type
    end
  end

  attribute :name, Types::Strict::String
  attribute :tags, Types::Strict::Array.of(Tag)
end


p x = EntityWorking.new("name" => "Franz", tags: [ {name: "red"}])
p x.new(name: "asdf")

p x = EntityFailing.new("name" => "Franz", tags: %w(red))
p x.new(name: "asdf")
```

```bash
#<EntityWorking name="Franz" tags=[#<Tag name="red">]>
#<EntityWorking name="asdf" tags=[#<Tag name="red">]>
#<EntityFailing name="Franz" tags=[#<Tag name="red">]>
/home/simon/.rvm/gems/ruby-2.4.0@guidebook-rails/gems/dry-struct-0.5.0/lib/dry/struct/class_interface.rb:208:in `rescue in new': [EntityFailing.new] [#<Tag name="red">] (Array) has invalid type for :tags violates constraints ([Tag.new] #<Tag name="red"> (Tag) has invalid type for :name violates constraints (type?(String, #<Tag name="red">) failed) failed) (Dry::Struct::Error)
        from /home/simon/.rvm/gems/ruby-2.4.0@guidebook-rails/gems/dry-struct-0.5.0/lib/dry/struct/class_interface.rb:202:in `new'
        from /home/simon/.rvm/gems/ruby-2.4.0@guidebook-rails/gems/dry-struct-0.5.0/lib/dry/struct/class_interface.rb:218:in `call'
        from /home/simon/.rvm/gems/ruby-2.4.0@guidebook-rails/gems/dry-struct-0.5.0/lib/dry/struct.rb:174:in `new'
        from dry_problem.rb:46:in `<main>'

shell returned 1
```

**Comment by GustavoCaso** [comment]
@lister I manage to fix work script by replacing `EntityFailing` with:

```ruby
class EntityFailing < Dry::Struct
  transform_keys(&:to_sym)

  transform_types do |type, name|
    case name
    when :tags
      then type.constructor do |tags|
        tags.map { |t| t.class == Tag ? t : Tag.new(name: t) }
      end
    else
      type
    end
  end

  attribute :name, Types::Strict::String
  attribute :tags, Types::Strict::Array.of(Tag)
end
```

I think I can explain what is happening to the first time in line `x = EntityFailing.new("name" => "Franz", tags: %w(red))` will execute the block of `transform_types` and when execute the line `x.new(name: "asdf")` will use the previous attributes `{name: "Franz" tags: [#<Tag name="red">]}` and merge `{name: "asdf"}` and trigger `tranform_types` so the second times the block parameters `tags` is already a `Tag` entity.

I would not jump to conclusions saying that this is a bug or the way you are using `transform_type` is the best way, but I'm sure @flash-gordon could throw some light on the subject.

**Comment by lister** [comment]
thx for the clarification. i will close this issue.

**Comment by flash-gordon** [comment]
The issue has nothing to do with `transform_types`, you'll get the same result with

```ruby
class EntityFailing < Dry::Struct
  transform_keys(&:to_sym)

  attribute :name, Types::Strict::String
  attribute :tags, Types::Strict::Array.of(Tag).constructor { |tags|
    tags.map { |t| Tag.new(name: t) }
   }
end
```

@lister your type for the `:tags` attribute doesn't support array of `Tag`s as input, it works with arrays of strings only. That's fine when you instantiate a struct for the first time with strings. However, when you call `x.new(update)` what it does essentially is `Entity.new(x.attributes.merge(update))`, here `x.attributes[:tags]` contains an array of `Tag` objects rather than an array of strings, hence the error. @GustavoCaso worked around that by making `constructor` work with both types of arrays.

**Comment by GustavoCaso** [comment]
@flash-gordon thanks for the comment and the clarification 😄
