### ISSUE TITLE
Adding computed/dynamic attributes

### ISSUE THREAD

**Issue by iakobos** [dry-rb/dry-struct#89]
I would like the ability to create computed attributes on my struct that call a method on `self` instead of taking a value in the initializer.

```ruby
class Person < Dry::Struct
  attribute :first_name, Types::Strict::String
  attribute :last_name, Types::Strict::String
  attribute :full_name, Types::Strict::String

  def full_name
    "#{first_name} #{last_name}"
  end
end

john = Person.new(first_name: "John", last_name: "Doe")
john.to_hash # => { first_name: "John", last_name: "Doe", full_name: "John Doe" }
```

It doesn't seem like there is (currently) a way to do this. I tried just making the attribute `ommittable: true`, since it seemed like https://github.com/dry-rb/dry-struct/blob/d34ec0e9fd6aa0eb5fee5264fef6fa45af900475/lib/dry/struct/class_interface.rb#L138 would allow me to define my own getter, but since things like `Struct#[]` and `Struct#to_hash` use the `@attributes` Hash directly, the getter method isn't called.

My initial thought is to create a PR that changes https://github.com/dry-rb/dry-struct/blob/d34ec0e9fd6aa0eb5fee5264fef6fa45af900475/lib/dry/struct.rb#L123 to be:
```
@attributes.fetch(name) { send(name) if respond_to?(name) }
```
but I wanted to check in with the maintainers before attempting this.

Thanks!

**Comment by flash-gordon** [comment]
At this point, I can't see how this can be useful, converting structs to hashes is a separate concern, generally speaking. If you have problems with this, you probably want to add a special kind of object for conversion/serialization. Please, raise questions like this on the gitter channel or discuss, as mentioned in the [guidelines](https://github.com/dry-rb/dry-struct/blob/master/CONTRIBUTING.md).
