### ISSUE TITLE
Anonymous struct doesn't work because of dry-container

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-struct#9]
I try use anonymous structs based on my simple struct.
And it doesn't work because of error 

    Dry::Container::Error: Nothing registered with the key "#"

You can quickly reproduce it with:

```ruby
class MyStruct < Dry::Types::Struct
  attribute :my_attr, Types::Strict::String
end
Dry::Types[MyStruct]
# => MyStruct
Dry::Types[Class.new(MyStruct)]
# Dry::Container::Error: Nothing registered with the key "#"
```

The reason of this is https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/hash.rb#L10, where it casts type, whenever it String or Class

**Comment by solnic** [comment]
I think we should look into removing auto-registration of struct descendants in the registry, it should not be needed anymore, I've added this when we didn't have a way of defining type constants.

**Comment by rocknruby** [comment]
Any workaround @Kukunin ?

**Comment by solnic** [comment]
@rocknruby dry-struct 0.1.0 no longer registers classes in the types registry, so it's no longer a problem

**Comment by rocknruby** [comment]
👍
