### ISSUE TITLE
Resolving default values on nil

### ISSUE THREAD

**Issue by macosgrove** [dry-rb/dry-struct#90]
Hi DRY team

`dry-struct 0.5.0`

In your [recipes for dry-struct](http://dry-rb.org/gems/dry-struct/recipes/) under the heading "Resolving default values on nil", you state:

```nil as a value isn’t replaced with a default value for default types.```

I have found that's not the case. Here's an RSpec test:

```ruby
require 'dry-types'
require 'dry-struct'

RSpec.describe Dry::Struct do

  module Types
    include Dry::Types.module
  end


  class User < Dry::Struct
    attribute :name, Types::String
    attribute :age, Types::Integer.default(18)
  end

  context 'when the key is missing' do
    let(:user) { User.new(name: 'Jane') }

    it 'sets the default' do
      expect(user.age).to eq 18
    end
  end

  context 'when the key is present but the value is nil' do
    let(:user) { User.new(name: 'Jane', age: nil) }

    it 'returns nil' do
      expect(user.age).to be_nil
    end
  end
end
```

The first example passes, but the second fails with:
```shell
  1) Dry::Struct when the key is present but the value is nil returns nil
     Failure/Error: expect(user.age).to be_nil

       expected: nil
            got: 18
```

Thanks for looking into this.

**Comment by macosgrove** [comment]
Some context: I'm trying to maintain existing behaviour on updating from dry-types 0.12.3 to 0.13.2. We were using `constructor_type :schema` and also `constructor_type: strict_with_defaults` and I'm trying to figure out replacements with the new syntax.

**Comment by flash-gordon** [comment]
Hey. It looks like a bug, but it's in dry-types. You might want to use strict types instead, they work fine:

```ruby
gordon@gordon ~/dev/dry-rb/dry-types (master) $ ./bin/console
[1] pry(main)> Types::Integer.default(18)
=> #<Dry::Types::Default type=#<Dry::Types::Definition primitive=Integer options={} meta={}> options={} value=18>
[2] pry(main)> Types::Integer.default(18)[nil]
=> 18
[3] pry(main)> Types::Strict::Integer.default(18)[nil]
Dry::Types::ConstraintError: nil violates constraints (type?(Integer, nil) failed)
from /Users/gordon/dev/dry-rb/dry-types/lib/dry/types/constrained.rb:28:in `block in call'
```

I'll have another look later

**Comment by GustavoCaso** [comment]
@flash-gordon I was able to track where the error is happening.
https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/default.rb#L71

Looks like `Default` when the output is `nil`it returns the `evaluate` which is the default value

**Comment by timriley** [comment]
@macosgrove in your issue here you've described the "Resolving default values on nil" recipe, but you're not actually using the suggested `transform_types` block from the recipe in your spec.

What behaviour do you actually need to see in your application?

**Comment by timriley** [comment]
I would also second @flash-gordon's suggestion to use strict types for your struct attributes.

The plain default types (the ones without the `Strict` namespace) will actually allow any values, which is not what you would want for typed struct classes.

**Comment by macosgrove** [comment]
@timriley I have not used the `transform_types` block in my spec because I want the _opposite_ of the behaviour that is intended to achieve. That `transform_types` block is intended to ensure that the default value is used even if the key is present with a nil value. In the absence of that block I expect the value to remain as nil if the key is present with a nil value. Instead, it gets set to the default despite the missing `transform_types` block.

In my app I have 30 or 40 schemas. We embed them in two different containers - in one context we use `constructor_type: strict_with_defaults` and in another context we use `constructor_type: schema`. I am trying to replicate the existing behaviour without those deprecated `constructor_type` lines. I don't think it's possible without [the suggested fix](https://github.com/dry-rb/dry-types/pull/259).

**Comment by macosgrove** [comment]
@timriley Thanks for that! My next task is to see if I can reproduce the strictness of `constructor_type: strict_with_defaults`. The [docs](http://dry-rb.org/gems/dry-struct/recipes/) recommend `input input.strict`. Unfortunately that seems to be incompatible with your `.new` override. This test fails:

```ruby
require 'dry-types'
require 'dry-struct'

RSpec.describe Dry::Struct do

  module Types
    include Dry::Types.module
  end

  class User < Dry::Struct
    input input.strict

    def self.new(attrs)
      attrs = input.member_types.each_with_object({}) { |(member_key, v), input_attrs|
        puts "Member key #{member_key}"
        puts "Value #{v}"
        puts "input attrs #{input_attrs}"
        input_attrs[member_key] = attrs.key?(member_key) ? attrs[member_key] : Dry::Types::Undefined
      }

      super(attrs)
    end

    attribute :name, Types::String
    attribute :age, Types::Integer.default(18).optional
  end

  context 'a required attribute without a default is missing' do
    it 'raises an error' do
      expect { User.new(age: 19) }.to raise_error(Dry::Struct::Error, /:name/)
    end
  end

  context 'an optional attribute with a default is missing' do
    it 'does not raise an error' do
      expect { User.new(name: 'Joe') }.not_to raise_error
    end
  end

  context 'an unknown attribute is added' do
    it 'raises an error' do
      expect { User.new(name: 'Joe', age: 15, foo: 'bar') }.to raise_error(Dry::Struct::Error, /:foo/)
    end
  end
end

```
with 

```shell
Failures:

  1) Dry::Struct a required attribute without a default is missing raises an error
     Failure/Error: expect { User.new(age: 19) }.to raise_error(Dry::Struct::Error, /:name/)
       expected Dry::Struct::Error with message matching /:name/ but nothing was raised
     # ./spec/test2_spec.rb:30:in `block (3 levels) in <top (required)>'

  2) Dry::Struct an unknown attribute is added raises an error
     Failure/Error: expect { User.new(name: 'Joe', age: 15, foo: 'bar') }.to raise_error(Dry::Struct::Error, /:foo/)
       expected Dry::Struct::Error with message matching /:foo/ but nothing was raised
     # ./spec/test2_spec.rb:42:in `block (3 levels) in <top (required)>'

Finished in 0.25332 seconds (files took 2.29 seconds to load)
3 examples, 2 failures
```

**Comment by timriley** [comment]
@macosgrove That's because the `input.member_types.each_with_object({})` part of that custom `.new` builds an input attrs hash based only on the attributes defined in the struct.

You'll want to do something like this:

```ruby
attrs_with_nil_values_reaplced_by_undefined = input.member_types.each_with_object({}) { |(member_key, _), input_attrs|
      input_attrs[member_key] = attrs.key?(member_key) ? attrs[member_key] : Dry::Types::Undefined
    }

attrs_with_unknown_keys_preserved = attrs.merge(attrs_with_nil_values_reaplced_by_undefined)

super(attrs_with_unknown_keys_preserved)
```

**Comment by timriley** [comment]
And to make `'a required attribute without a default is missing'` work you'll need to change the block args to ` { |(member_key, member_type)` and only provide `Dry::Types::Undefined` if the type has a default.

Also you need to convert all your types to be `Strict` types, like we've been suggesting earlier.

**Comment by flash-gordon** [comment]
The fix will be included in the next dry-types release
